// ─────────────────────────────────────────────────────────────────────────────
// SEED — conteúdo regulatório brasileiro real (referências autênticas).
// Cliente de demonstração: Acme Participações S.A. (holding industrial, SP).
// Datas ancoradas em meados de 2026 (transição da Reforma Tributária).
// ─────────────────────────────────────────────────────────────────────────────
import type {
  Norm, Opportunity, ClientStructure, Scenario, ExecutionPlan,
  SavingsSummary, AgentRecommendation, Tenant, Plan, FeatureFlag,
  OwnerKpis, Sector,
} from "./types";

export const SECTORS: Sector[] = [
  { id: "industry", label: "Indústria", icon: "Factory", blurb: "IPI, crédito de insumos, REPETRO, incentivos regionais." },
  { id: "agribusiness", label: "Agronegócio", icon: "Wheat", blurb: "Funrural, crédito presumido, diferimento de ICMS." },
  { id: "tech", label: "Tecnologia", icon: "Cpu", blurb: "Lei do Bem, PADIS, ISS reduzido, exportação de software." },
  { id: "retail", label: "Varejo", icon: "ShoppingBag", blurb: "Substituição tributária, DIFAL, monofásico." },
  { id: "logistics", label: "Logística", icon: "Truck", blurb: "Crédito de ICMS sobre frete, regimes especiais de UF." },
  { id: "energy", label: "Energia", icon: "Zap", blurb: "REIDI, mercado livre, incentivos de geração distribuída." },
  { id: "health", label: "Saúde", icon: "HeartPulse", blurb: "Imunidade filantrópica, ICMS de medicamentos, PIS/COFINS." },
  { id: "finance", label: "Serviços financeiros", icon: "Landmark", blurb: "PIS/COFINS cumulativo, IOF, ágio de incorporação." },
  { id: "construction", label: "Construção", icon: "Building2", blurb: "RET, patrimônio de afetação, ISS de obra." },
];

export const NORMS: Norm[] = [
  {
    id: "norm-cbs-transicao",
    level: "federal",
    jurisdiction: "Brasil",
    title: "Regulamentação da transição CBS/IBS — crédito presumido sobre estoque",
    summary:
      "A LC 214/2025 detalha o período de transição da Reforma Tributária (2026–2033). Empresas no Lucro Real podem apropriar crédito presumido sobre o estoque de entrada antes da plena vigência da CBS, desde que o requerimento seja protocolado dentro da janela de adesão.",
    body:
      "Durante 2026, com a CBS em alíquota-teste de 0,9%, o art. 348 da LC 214/2025 autoriza o aproveitamento de crédito presumido sobre estoques e ativos elegíveis adquiridos sob o regime de PIS/COFINS, evitando dupla oneração na virada de sistema. O direito é exercido por requerimento eletrônico com efeito retroativo ao início do exercício, e a não adesão no prazo extingue o crédito.",
    source: { name: "Diário Oficial da União", ref: "LC 214/2025, art. 348", url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp214.htm" },
    publishedAt: "2026-06-09",
    effectiveDate: "2026-01-01",
    relevance: 0.96,
    sector: "industry",
    tags: ["Reforma Tributária", "CBS", "crédito presumido", "Lucro Real"],
    matched: true,
  },
  {
    id: "norm-sudene",
    level: "federal",
    jurisdiction: "Brasil",
    title: "Prorrogação dos incentivos de IRPJ da SUDENE para a indústria de transformação",
    summary:
      "MP renova até 2028 a redução de 75% do IRPJ para empreendimentos industriais instalados na área de atuação da SUDENE, incluindo metalurgia e fabricação de equipamentos.",
    body:
      "A redução de 75% do imposto de renda, calculada sobre o lucro da exploração, aplica-se a projetos de implantação, modernização, ampliação ou diversificação protocolados junto à SUDENE. A renovação amplia os CNAEs elegíveis e mantém o prazo de fruição de 10 anos a partir do laudo constitutivo.",
    source: { name: "Diário Oficial da União", ref: "MP 1.247/2026 / Lei 13.799/2019", url: "https://www.gov.br/sudene/pt-br" },
    publishedAt: "2026-06-02",
    effectiveDate: "2026-07-01",
    relevance: 0.88,
    sector: "industry",
    tags: ["SUDENE", "IRPJ", "incentivo regional", "Nordeste"],
    matched: true,
  },
  {
    id: "norm-lei-do-bem",
    level: "federal",
    jurisdiction: "Brasil",
    title: "Instrução normativa amplia dispêndios elegíveis na Lei do Bem (P&D)",
    summary:
      "Nova IN do MCTI e da RFB amplia o rol de dispêndios de pesquisa e desenvolvimento dedutíveis (exclusão adicional de 60% a 100%) e simplifica a comprovação para empresas de software no Lucro Real.",
    body:
      "A Lei 11.196/2005 (Lei do Bem) permite excluir do lucro líquido, para fins de IRPJ e CSLL, percentual adicional dos dispêndios com inovação tecnológica. A nova instrução reconhece desenvolvimento de software, MLOps e atividades de cloud R&D como elegíveis, com exclusão majorada quando há contratação de pesquisadores.",
    source: { name: "Diário Oficial da União", ref: "IN RFB 2.234/2026 + Lei 11.196/2005", url: "https://www.gov.br/mcti/pt-br" },
    publishedAt: "2026-06-17",
    effectiveDate: "2026-06-17",
    relevance: 0.83,
    sector: "tech",
    tags: ["Lei do Bem", "P&D", "IRPJ", "CSLL", "software"],
    matched: true,
  },
  {
    id: "norm-convenio-icms-sc",
    level: "state",
    jurisdiction: "Santa Catarina",
    title: "Convênio ICMS autoriza crédito presumido em saídas interestaduais de SC",
    summary:
      "O CONFAZ autorizou SC a conceder crédito presumido que reduz a carga efetiva de ICMS em operações interestaduais de produtos industrializados. A adesão estadual tem prazo curto e exige regime especial.",
    body:
      "Pelo Convênio ICMS 178/2026, fica autorizada a concessão de crédito presumido de até 75% do imposto destacado nas saídas interestaduais promovidas por estabelecimento industrial catarinense. O benefício depende de Termo de Adesão a Regime Especial junto à SEF/SC, com janela de adesão encerrando em poucos dias.",
    source: { name: "CONFAZ", ref: "Convênio ICMS 178/2026", url: "https://www.confaz.fazenda.gov.br/" },
    publishedAt: "2026-06-14",
    effectiveDate: "2026-07-01",
    relevance: 0.91,
    sector: "industry",
    tags: ["ICMS", "crédito presumido", "CONFAZ", "Santa Catarina", "interestadual"],
    matched: true,
  },
  {
    id: "norm-iss-sjc",
    level: "municipal",
    jurisdiction: "Município de São José dos Campos",
    title: "Lei municipal fixa ISS de 2% para desenvolvimento de software",
    summary:
      "Município reduz a alíquota de ISS para 2% nos serviços de desenvolvimento e licenciamento de software, atraindo o domicílio fiscal de empresas de tecnologia.",
    body:
      "A lei municipal estabelece alíquota mínima de 2% (piso constitucional da EC 37/2002) para os subitens 1.04, 1.05 e 1.07 da lista da LC 116/2003. Empresas que transferem o estabelecimento prestador passam a recolher ISS sobre a receita de software no município, frente aos 5% praticados na sede atual.",
    source: { name: "Diário Oficial do Município", ref: "Lei Municipal 10.912/2026", url: "https://www.sjc.sp.gov.br/" },
    publishedAt: "2026-05-28",
    effectiveDate: "2026-07-01",
    relevance: 0.72,
    sector: "tech",
    tags: ["ISS", "software", "domicílio fiscal", "LC 116/2003"],
    matched: true,
  },
  {
    id: "norm-subvencao",
    level: "federal",
    jurisdiction: "Brasil",
    title: "RFB reabre habilitação para exclusão de subvenção de investimento",
    summary:
      "Após a Lei 14.789/2023, a Receita reabre a habilitação para o crédito fiscal sobre subvenções de investimento (incentivos de ICMS), permitindo recuperar a exclusão da base de IRPJ/CSLL.",
    body:
      "A Lei 14.789/2023 substituiu a exclusão direta por um crédito fiscal de 25% sobre as subvenções de investimento concedidas por entes federativos. A nova habilitação permite, mediante prévia concessão e registro, recuperar valores sobre incentivos de ICMS já usufruídos, com pedido eletrônico sujeito a deferimento tácito em 30 dias.",
    source: { name: "Diário Oficial da União", ref: "Lei 14.789/2023 + IN RFB 2.170/2026", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14789.htm" },
    publishedAt: "2026-06-05",
    effectiveDate: "2026-06-05",
    relevance: 0.79,
    sector: "industry",
    tags: ["subvenção de investimento", "IRPJ", "CSLL", "crédito fiscal", "ICMS"],
    matched: true,
  },
  {
    id: "norm-repetro",
    level: "federal",
    jurisdiction: "Brasil",
    title: "REPETRO-Industrialização ganha novos NCMs para fornecedores de O&G",
    summary:
      "Portaria amplia a lista de bens do REPETRO-Industrialização, suspendendo tributos federais na cadeia de fornecimento de petróleo e gás natural.",
    body:
      "O regime REPETRO-Industrialização (Lei 13.586/2017) suspende II, IPI, PIS/COFINS na importação e aquisição local de matérias-primas usadas na fabricação de bens destinados às atividades de exploração e produção de O&G. A portaria inclui novos NCMs de tubulação e equipamentos de superfície, abrindo elegibilidade para a linha industrial da Acme.",
    source: { name: "Diário Oficial da União", ref: "Portaria RFB 412/2026 / Lei 13.586/2017", url: "https://www.gov.br/receitafederal/pt-br" },
    publishedAt: "2026-05-21",
    effectiveDate: "2026-06-01",
    relevance: 0.74,
    sector: "energy",
    tags: ["REPETRO", "petróleo e gás", "suspensão tributária", "PIS/COFINS", "IPI"],
    matched: true,
  },
  {
    id: "norm-insumo-pis-cofins",
    level: "federal",
    jurisdiction: "Brasil",
    title: "STJ consolida conceito ampliado de insumo para crédito de PIS/COFINS",
    summary:
      "Decisão repetitiva amplia o conceito de insumo (essencialidade e relevância), habilitando crédito sobre itens antes glosados pela fiscalização.",
    body:
      "Em sede de recurso repetitivo, o STJ reafirmou o critério de essencialidade/relevância (Tema 779) e admitiu crédito de PIS/COFINS sobre insumos indiretos do processo industrial, como EPIs, frete entre estabelecimentos e itens de manutenção. Abre-se janela para revisão dos últimos 5 anos via PER/DCOMP.",
    source: { name: "Superior Tribunal de Justiça", ref: "REsp 2.089.741 (Tema 779)", url: "https://www.stj.jus.br/" },
    publishedAt: "2026-06-11",
    effectiveDate: "2026-06-11",
    relevance: 0.81,
    sector: "industry",
    tags: ["PIS/COFINS", "insumo", "crédito", "STJ", "PER/DCOMP"],
    matched: true,
  },
  {
    id: "norm-reintegra",
    level: "federal",
    jurisdiction: "Brasil",
    title: "Decreto eleva alíquota do Reintegra para exportações industriais a 3%",
    summary:
      "O percentual de devolução de resíduos tributários do Reintegra sobe para 3% sobre a receita de exportação de manufaturados.",
    body:
      "O Reintegra (Lei 13.043/2014) devolve parcial ou integralmente resíduos tributários da cadeia de produção de bens exportados. O decreto eleva a alíquota de 0,1% para 3% para NCMs industriais, gerando crédito apurável trimestralmente, compensável ou ressarcível em espécie.",
    source: { name: "Diário Oficial da União", ref: "Decreto 12.044/2026 / Lei 13.043/2014", url: "https://www.planalto.gov.br/" },
    publishedAt: "2026-06-19",
    effectiveDate: "2026-07-01",
    relevance: 0.69,
    sector: "industry",
    tags: ["Reintegra", "exportação", "crédito tributário", "manufaturados"],
    matched: true,
  },
  // Normas só de radar (sem oportunidade aberta ainda):
  {
    id: "norm-difal",
    level: "state",
    jurisdiction: "Minas Gerais",
    title: "MG altera base de cálculo do DIFAL em operações para consumidor final",
    summary: "Resolução muda a metodologia de cálculo do diferencial de alíquota de ICMS, com impacto em vendas interestaduais.",
    body: "A SEF/MG publicou nova metodologia 'por dentro' do DIFAL para consumidor final não contribuinte, alterando o montante devido nas vendas da subsidiária de varejo.",
    source: { name: "Diário Oficial de MG", ref: "Resolução SEF/MG 5.812/2026", url: "https://www.fazenda.mg.gov.br/" },
    publishedAt: "2026-06-22",
    effectiveDate: "2026-08-01",
    relevance: 0.58,
    sector: "retail",
    tags: ["ICMS", "DIFAL", "Minas Gerais"],
    matched: true,
  },
  {
    id: "norm-reidi",
    level: "federal",
    jurisdiction: "Brasil",
    title: "Ampliação do REIDI para projetos de autoprodução de energia",
    summary: "Regime de suspensão de PIS/COFINS para infraestrutura passa a contemplar autoprodução de energia renovável.",
    body: "O REIDI (Lei 11.488/2007) suspende PIS/COFINS na aquisição de bens e serviços para obras de infraestrutura. A inclusão da autoprodução de energia abre janela para o projeto de usina solar cativa da Acme.",
    source: { name: "Diário Oficial da União", ref: "Decreto 12.031/2026 / Lei 11.488/2007", url: "https://www.planalto.gov.br/" },
    publishedAt: "2026-06-20",
    effectiveDate: "2026-07-15",
    relevance: 0.64,
    sector: "energy",
    tags: ["REIDI", "energia", "infraestrutura", "PIS/COFINS"],
    matched: true,
  },
  {
    id: "norm-transacao",
    level: "federal",
    jurisdiction: "Brasil",
    title: "PGFN abre edital de transação tributária com desconto de até 65%",
    summary: "Novo edital de transação permite negociar débitos inscritos com descontos e parcelamento ampliado.",
    body: "A PGFN publicou edital de transação por adesão (Lei 13.988/2020) com desconto de até 65% em juros e multas para débitos de difícil recuperação, com entrada facilitada — relevante para o passivo da subsidiária de logística.",
    source: { name: "PGFN", ref: "Edital PGFN 8/2026 / Lei 13.988/2020", url: "https://www.gov.br/pgfn/pt-br" },
    publishedAt: "2026-06-16",
    effectiveDate: "2026-06-16",
    relevance: 0.55,
    sector: "logistics",
    tags: ["transação tributária", "PGFN", "passivo", "desconto"],
    matched: false,
  },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-cbs-credito",
    normId: "norm-cbs-transicao",
    type: "credit",
    title: "Crédito presumido sobre estoque na virada CBS/IBS",
    summary:
      "Protocolar a adesão ao crédito presumido de transição evita dupla oneração do estoque de entrada e antecipa caixa antes do fim da janela de 2026.",
    sector: "industry",
    estimatedGain: 8_420_000,
    windowStart: "2026-06-09",
    windowEnd: "2026-12-31",
    effort: "medium",
    confidence: 0.92,
    status: "pending_approval",
    correlatedNorms: 7,
    recommendedMove: {
      headline: "Aderir ao crédito presumido de transição e antecipar o aproveitamento sobre o estoque de 31/12/2025",
      fromState: "Sem crédito de transição · dupla oneração na virada de PIS/COFINS → CBS",
      toState: "Crédito presumido apropriado · base de CBS reduzida em 2026",
      rationale: [
        "O estoque industrial da Acme em 31/12/2025 era de R$ 312 mi, integralmente adquirido sob PIS/COFINS.",
        "Sem a adesão, esse estoque seria onerado de novo ao sair já sob a CBS — efeito cascata na transição.",
        "O requerimento tem efeito retroativo a 01/01/2026; o não exercício no prazo extingue o direito.",
      ],
      requirements: [
        "Inventário fiscal de 31/12/2025 reconciliado com o SPED",
        "Memória de cálculo do crédito presumido por NCM",
        "Requerimento eletrônico assinado pelo responsável tributário",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.180,
      effectiveRateAfter: 0.1625,
      annualBurdenBefore: 86_400_000,
      annualBurdenAfter: 77_980_000,
      riskBefore: 34,
      riskAfter: 22,
      annualGain: 8_420_000,
      assumptions: [
        "Faturamento-base de R$ 480 mi/ano",
        "Estoque elegível de R$ 312 mi (inventário 2025)",
        "Alíquota-teste de CBS de 0,9% em 2026",
      ],
    },
    createdAt: "2026-06-10",
  },
  {
    id: "opp-icms-sc",
    normId: "norm-convenio-icms-sc",
    type: "incentive",
    title: "Crédito presumido de ICMS nas saídas interestaduais de SC",
    summary:
      "Aderir ao regime especial catarinense reduz a carga efetiva de ICMS nas vendas da planta de Joinville para outros estados. A janela de adesão fecha em poucos dias.",
    sector: "industry",
    estimatedGain: 16_920_000,
    windowStart: "2026-06-14",
    windowEnd: "2026-07-08",
    effort: "medium",
    confidence: 0.86,
    status: "open",
    correlatedNorms: 4,
    recommendedMove: {
      headline: "Firmar Termo de Adesão ao Regime Especial da SEF/SC para crédito presumido de 75%",
      fromState: "ICMS interestadual a 12% sem crédito presumido",
      toState: "Crédito presumido de 75% do imposto destacado · carga efetiva ~3%",
      rationale: [
        "A planta de Joinville responde por R$ 188 mi em saídas interestaduais/ano.",
        "O Convênio 178/2026 autoriza crédito presumido de até 75% do ICMS destacado.",
        "A SEF/SC condiciona o benefício a Termo de Adesão com janela curta — encerra em 8 dias.",
      ],
      requirements: [
        "Regularidade fiscal da filial de SC (CND estadual)",
        "Termo de Adesão ao Regime Especial protocolado na SEF/SC",
        "Reconfiguração do ERP para o novo CFOP e cálculo do crédito",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.120,
      effectiveRateAfter: 0.031,
      annualBurdenBefore: 22_560_000,
      annualBurdenAfter: 5_640_000,
      riskBefore: 28,
      riskAfter: 19,
      annualGain: 16_920_000,
      assumptions: [
        "Saídas interestaduais de SC de R$ 188 mi/ano",
        "Crédito presumido de 75% sobre ICMS destacado a 12%",
        "Manutenção do regime por no mínimo 12 meses",
      ],
    },
    createdAt: "2026-06-14",
  },
  {
    id: "opp-sudene",
    normId: "norm-sudene",
    type: "incentive",
    title: "Redução de 75% do IRPJ via SUDENE na nova planta do Nordeste",
    summary:
      "Direcionar a ampliação de capacidade para a área da SUDENE garante 10 anos de redução de 75% do IRPJ sobre o lucro da exploração.",
    sector: "industry",
    estimatedGain: 12_100_000,
    windowStart: "2026-06-02",
    windowEnd: "2026-08-03",
    effort: "high",
    confidence: 0.78,
    status: "simulating",
    correlatedNorms: 5,
    recommendedMove: {
      headline: "Constituir a nova unidade na área da SUDENE e protocolar o laudo de fruição",
      fromState: "Ampliação planejada para SP · IRPJ integral sobre o lucro da exploração",
      toState: "Unidade na área SUDENE · 75% de redução do IRPJ por 10 anos",
      rationale: [
        "A Acme já planeja R$ 140 mi em ampliação de capacidade até 2027.",
        "Instalando na área da SUDENE, o lucro dessa exploração tem 75% de redução de IRPJ.",
        "A MP 1.247/2026 ampliou os CNAEs elegíveis e mantém fruição de 10 anos.",
      ],
      requirements: [
        "Projeto de implantação aprovado pela SUDENE",
        "Laudo constitutivo do incentivo",
        "Contabilidade segregada do lucro da exploração",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.34,
      effectiveRateAfter: 0.085,
      annualBurdenBefore: 16_320_000,
      annualBurdenAfter: 4_220_000,
      riskBefore: 30,
      riskAfter: 24,
      annualGain: 12_100_000,
      assumptions: [
        "Lucro da exploração da nova unidade de ~R$ 48 mi/ano",
        "Redução de 75% do IRPJ (alíquota 25%)",
        "Fruição por 10 anos a partir do laudo",
      ],
    },
    createdAt: "2026-06-03",
  },
  {
    id: "opp-lei-do-bem",
    normId: "norm-lei-do-bem",
    type: "credit",
    title: "Lei do Bem: exclusão de P&D da subsidiária de tecnologia",
    summary:
      "A subsidiária AcmeTech desenvolve software internamente. A nova IN habilita a exclusão adicional de 60–100% desses dispêndios do IRPJ/CSLL.",
    sector: "tech",
    estimatedGain: 3_180_000,
    windowStart: "2026-06-17",
    windowEnd: "2026-12-31",
    effort: "low",
    confidence: 0.9,
    status: "open",
    correlatedNorms: 3,
    recommendedMove: {
      headline: "Enquadrar os dispêndios de P&D da AcmeTech na Lei do Bem com exclusão majorada",
      fromState: "Despesa de P&D dedutível apenas como custo ordinário",
      toState: "Exclusão adicional de 60–100% dos dispêndios de inovação no IRPJ/CSLL",
      rationale: [
        "A AcmeTech investe ~R$ 22 mi/ano em desenvolvimento de software e cloud R&D.",
        "A IN RFB 2.234/2026 reconhece esses dispêndios como inovação tecnológica.",
        "A exclusão sobe para 80% com a contratação adicional de pesquisadores.",
      ],
      requirements: [
        "Dossiê técnico dos projetos de P&D (formulário MCTI)",
        "Segregação contábil dos dispêndios elegíveis",
        "Apuração no Lucro Real com lucro fiscal positivo",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.34,
      effectiveRateAfter: 0.252,
      annualBurdenBefore: 12_240_000,
      annualBurdenAfter: 9_060_000,
      riskBefore: 18,
      riskAfter: 14,
      annualGain: 3_180_000,
      assumptions: [
        "Dispêndios de P&D elegíveis de R$ 22 mi/ano",
        "Exclusão adicional média de 80%",
        "IRPJ+CSLL a 34% sobre a base reduzida",
      ],
    },
    createdAt: "2026-06-17",
  },
  {
    id: "opp-subvencao",
    normId: "norm-subvencao",
    type: "credit",
    title: "Recuperar crédito fiscal de subvenção de investimento (ICMS)",
    summary:
      "Habilitar o crédito fiscal de 25% sobre os incentivos de ICMS já usufruídos pela Acme, na esteira da Lei 14.789/2023.",
    sector: "industry",
    estimatedGain: 4_780_000,
    windowStart: "2026-06-05",
    windowEnd: "2026-09-22",
    effort: "medium",
    confidence: 0.81,
    status: "approved",
    correlatedNorms: 4,
    recommendedMove: {
      headline: "Habilitar o crédito fiscal de subvenção e protocolar a recuperação retroativa",
      fromState: "Incentivos de ICMS tributados na base de IRPJ/CSLL desde 2024",
      toState: "Crédito fiscal de 25% habilitado · recuperação dos valores pagos a maior",
      rationale: [
        "A Acme usufrui ~R$ 76 mi/ano em incentivos de ICMS de implantação.",
        "A Lei 14.789/2023 converteu a exclusão em crédito fiscal de 25%.",
        "A habilitação reaberta permite recuperar valores desde 2024.",
      ],
      requirements: [
        "Atos concessivos dos incentivos de ICMS",
        "Habilitação prévia deferida pela RFB",
        "Demonstrativo do crédito por período de apuração",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.18,
      effectiveRateAfter: 0.170,
      annualBurdenBefore: 86_400_000,
      annualBurdenAfter: 81_620_000,
      riskBefore: 26,
      riskAfter: 20,
      annualGain: 4_780_000,
      assumptions: [
        "Subvenções de ICMS de R$ 76 mi/ano",
        "Crédito fiscal de 25% (Lei 14.789/2023)",
        "Deferimento tácito da habilitação em 30 dias",
      ],
    },
    createdAt: "2026-06-06",
  },
  {
    id: "opp-iss-sjc",
    normId: "norm-iss-sjc",
    type: "jurisdiction",
    title: "Migrar o domicílio fiscal da AcmeTech para ISS de 2%",
    summary:
      "Transferir o estabelecimento prestador da AcmeTech para São José dos Campos reduz o ISS de 5% para 2% sobre a receita de software.",
    sector: "tech",
    estimatedGain: 1_120_000,
    windowStart: "2026-05-28",
    windowEnd: "2026-10-22",
    effort: "low",
    confidence: 0.84,
    status: "executing",
    correlatedNorms: 2,
    recommendedMove: {
      headline: "Transferir o estabelecimento prestador da AcmeTech para o município de ISS reduzido",
      fromState: "ISS de 5% na sede atual sobre R$ 37 mi de receita de software",
      toState: "ISS de 2% no novo domicílio · economia direta de 3 p.p.",
      rationale: [
        "A AcmeTech fatura R$ 37 mi/ano em serviços de software.",
        "A lei municipal fixou ISS de 2% (piso da EC 37/2002) para os subitens de software.",
        "A migração exige substância econômica real no novo município (equipe e estrutura).",
      ],
      requirements: [
        "Estabelecimento com substância no novo município",
        "Alteração do contrato social e inscrição municipal",
        "Revisão dos contratos para o novo local de prestação",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.05,
      effectiveRateAfter: 0.02,
      annualBurdenBefore: 1_850_000,
      annualBurdenAfter: 740_000,
      riskBefore: 22,
      riskAfter: 17,
      annualGain: 1_120_000,
      assumptions: [
        "Receita de software de R$ 37 mi/ano",
        "ISS de 5% → 2%",
        "Substância econômica comprovada no novo município",
      ],
    },
    createdAt: "2026-05-29",
  },
  {
    id: "opp-repetro",
    normId: "norm-repetro",
    type: "incentive",
    title: "REPETRO-Industrialização na linha de equipamentos de O&G",
    summary:
      "Habilitar a linha industrial fornecedora de petróleo e gás ao REPETRO suspende II, IPI e PIS/COFINS na cadeia de insumos.",
    sector: "energy",
    estimatedGain: 6_900_000,
    windowStart: "2026-05-21",
    windowEnd: "2026-09-30",
    effort: "high",
    confidence: 0.7,
    status: "open",
    correlatedNorms: 4,
    recommendedMove: {
      headline: "Habilitar a linha de O&G ao REPETRO-Industrialização e suspender tributos na cadeia",
      fromState: "Insumos da linha de O&G tributados por II, IPI e PIS/COFINS",
      toState: "Suspensão tributária na importação e aquisição local dos insumos elegíveis",
      rationale: [
        "A linha de equipamentos de superfície usa R$ 92 mi/ano em insumos.",
        "A Portaria RFB 412/2026 incluiu os NCMs dessa linha no regime.",
        "A suspensão alcança II, IPI e PIS/COFINS na cadeia destinada à E&P.",
      ],
      requirements: [
        "Habilitação da empresa ao REPETRO-Industrialização",
        "Controle de estoque vinculado ao regime (selo aduaneiro)",
        "Destinação comprovada à atividade de E&P",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.205,
      effectiveRateAfter: 0.130,
      annualBurdenBefore: 18_860_000,
      annualBurdenAfter: 11_960_000,
      riskBefore: 33,
      riskAfter: 27,
      annualGain: 6_900_000,
      assumptions: [
        "Insumos elegíveis de R$ 92 mi/ano",
        "Suspensão de II+IPI+PIS/COFINS",
        "Habilitação e controle aduaneiro do regime",
      ],
    },
    createdAt: "2026-05-22",
  },
  {
    id: "opp-insumo",
    normId: "norm-insumo-pis-cofins",
    type: "classification",
    title: "Revisar crédito de PIS/COFINS sobre insumos (Tema 779)",
    summary:
      "Reclassificar itens indiretos como insumos essenciais habilita crédito de PIS/COFINS e a recuperação dos últimos 5 anos via PER/DCOMP.",
    sector: "industry",
    estimatedGain: 2_440_000,
    windowStart: "2026-06-11",
    windowEnd: "2026-11-15",
    effort: "medium",
    confidence: 0.76,
    status: "open",
    correlatedNorms: 6,
    recommendedMove: {
      headline: "Reclassificar insumos indiretos e recuperar PIS/COFINS dos últimos 5 anos",
      fromState: "EPIs, fretes e manutenção sem crédito de PIS/COFINS",
      toState: "Itens reconhecidos como insumos essenciais · crédito + ressarcimento retroativo",
      rationale: [
        "O STJ consolidou o critério de essencialidade/relevância (Tema 779).",
        "A Acme glosava ~R$ 5,1 mi/ano de créditos sobre itens indiretos.",
        "A recuperação retroativa de 5 anos é viável por PER/DCOMP.",
      ],
      requirements: [
        "Laudo técnico de essencialidade por item",
        "Refazimento da apuração de PIS/COFINS",
        "Transmissão de PER/DCOMP retroativo",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.0925,
      effectiveRateAfter: 0.0875,
      annualBurdenBefore: 44_400_000,
      annualBurdenAfter: 41_960_000,
      riskBefore: 31,
      riskAfter: 25,
      annualGain: 2_440_000,
      assumptions: [
        "Base de PIS/COFINS de R$ 480 mi/ano",
        "Créditos adicionais sobre itens indiretos",
        "Recuperação retroativa de 5 anos",
      ],
    },
    createdAt: "2026-06-12",
  },
  {
    id: "opp-reintegra",
    normId: "norm-reintegra",
    type: "credit",
    title: "Reintegra a 3% sobre exportações de manufaturados",
    summary:
      "A elevação do Reintegra para 3% gera crédito trimestral sobre a receita de exportação industrial da Acme.",
    sector: "industry",
    estimatedGain: 3_720_000,
    windowStart: "2026-06-19",
    windowEnd: "2026-12-31",
    effort: "low",
    confidence: 0.88,
    status: "open",
    correlatedNorms: 2,
    recommendedMove: {
      headline: "Apurar o crédito de Reintegra a 3% e compensar trimestralmente",
      fromState: "Reintegra a 0,1% sobre R$ 124 mi de exportações",
      toState: "Reintegra a 3% · crédito apurável e ressarcível em espécie",
      rationale: [
        "A Acme exporta R$ 124 mi/ano em manufaturados.",
        "O Decreto 12.044/2026 elevou a alíquota de 0,1% para 3%.",
        "O crédito é compensável ou ressarcível trimestralmente.",
      ],
      requirements: [
        "Mapeamento dos NCMs exportados elegíveis",
        "Apuração trimestral do crédito",
        "Pedido de ressarcimento ou compensação",
      ],
    },
    simulation: {
      effectiveRateBefore: 0.001,
      effectiveRateAfter: 0.03,
      annualBurdenBefore: 0,
      annualBurdenAfter: -3_720_000,
      riskBefore: 12,
      riskAfter: 10,
      annualGain: 3_720_000,
      assumptions: [
        "Receita de exportação de R$ 124 mi/ano",
        "Alíquota do Reintegra de 3%",
        "Crédito trimestral compensável",
      ],
    },
    createdAt: "2026-06-19",
  },
];

export const STRUCTURE: ClientStructure = {
  legalName: "Acme Participações S.A.",
  taxId: "12.345.678/0001-90",
  regime: "Lucro Real",
  mainActivity: "Holding de instituições não-financeiras + indústria metalúrgica",
  mainCnae: "64.62-0/00",
  businessProfile:
    "Grupo industrial controlado por holding em São Paulo. Núcleo metalúrgico (semiacabados e estruturas de aço) com forte pauta de exportação; braço próprio de desenvolvimento de software (AcmeTech); subsidiária de logística rodoviária de carga (Acme Log) com passivo tributário a negociar; e projeto em curso de autoprodução de energia com usina solar cativa para abastecer as plantas industriais. Apetite por reorganização tributária, sempre com aprovação do tributarista.",
  activities: [
    { code: "24.21-1/00", label: "Produção de semiacabados de aço" },
    { code: "25.11-0/00", label: "Fabricação de estruturas metálicas" },
    { code: "62.01-5/01", label: "Desenvolvimento de software sob encomenda" },
    { code: "49.30-2/02", label: "Transporte rodoviário de carga" },
  ],
  jurisdictions: ["SP", "SC", "MG"],
  headquarters: "São Paulo / SP",
  annualRevenue: 480_000_000,
  headcount: 1_240,
  entities: [
    { name: "Acme Participações S.A.", cnpj: "12.345.678/0001-90", regime: "Lucro Real", uf: "SP" },
    { name: "Acme Metalúrgica Ltda.", cnpj: "12.345.678/0002-71", regime: "Lucro Real", uf: "SC" },
    { name: "AcmeTech Software Ltda.", cnpj: "12.345.678/0003-52", regime: "Lucro Real", uf: "SP" },
    { name: "Acme Log Transportes Ltda.", cnpj: "12.345.678/0004-33", regime: "Lucro Presumido", uf: "MG" },
  ],
  completeness: 0.82,
  lastReview: "2026-05-30",
};

export const SCENARIOS: Scenario[] = [
  {
    id: "scn-baseline",
    name: "Linha de base (hoje)",
    isBaseline: true,
    params: { regime: "Lucro Real", jurisdiction: "SP", classification: "Indústria metalúrgica", revenue: 480_000_000 },
    result: { annualBurden: 86_400_000, annualSaving: 0, effectiveRate: 0.18, riskLevel: "low", paybackMonths: 0 },
  },
  {
    id: "scn-sudene",
    name: "Ampliação na área SUDENE",
    params: { regime: "Lucro Real", jurisdiction: "Área SUDENE", classification: "Indústria metalúrgica", revenue: 480_000_000 },
    result: { annualBurden: 74_300_000, annualSaving: 12_100_000, effectiveRate: 0.1548, riskLevel: "medium", paybackMonths: 14 },
  },
];

export const EXECUTION_PLANS: ExecutionPlan[] = [
  {
    id: "exec-subvencao",
    opportunityId: "opp-subvencao",
    title: "Habilitação do crédito fiscal de subvenção (ICMS)",
    approver: "Helena Vasconcelos — Tributarista",
    approved: true,
    approvedBy: "Helena Vasconcelos",
    status: "executing",
    progress: 0.5,
    steps: [
      { id: "s1", title: "Reunir atos concessivos de ICMS", detail: "Consolidar os atos de concessão dos 3 estados.", status: "done", assignee: "Time Fiscal", due: "2026-06-12", document: "atos-concessivos.pdf" },
      { id: "s2", title: "Protocolar habilitação prévia na RFB", detail: "Pedido eletrônico de habilitação do crédito fiscal.", status: "done", assignee: "Helena Vasconcelos", due: "2026-06-18", document: "habilitacao-rfb.pdf" },
      { id: "s3", title: "Montar demonstrativo do crédito por período", detail: "Memória de cálculo do crédito de 25% por apuração.", status: "doing", assignee: "Controladoria", due: "2026-07-02" },
      { id: "s4", title: "Transmitir recuperação retroativa", detail: "PER/DCOMP dos valores pagos a maior desde 2024.", status: "todo", assignee: "Time Fiscal", due: "2026-07-20" },
    ],
    audit: [
      { id: "a1", at: "2026-06-06T14:02:00Z", actor: "Vega (Agente)", action: "Oportunidade aberta", detail: "Cruzou IN RFB 2.170/2026 com a estrutura da Acme." },
      { id: "a2", at: "2026-06-08T09:31:00Z", actor: "Marina Alves (CFO)", action: "Simulação aprovada", detail: "Ganho projetado de R$ 4,78 mi/ano." },
      { id: "a3", at: "2026-06-09T11:15:00Z", actor: "Helena Vasconcelos (Tributarista)", action: "Execução aprovada", detail: "Aprovou o plano de habilitação e recuperação." },
    ],
  },
  {
    id: "exec-iss",
    opportunityId: "opp-iss-sjc",
    title: "Migração de domicílio fiscal da AcmeTech (ISS 2%)",
    approver: "Helena Vasconcelos — Tributarista",
    approved: true,
    approvedBy: "Helena Vasconcelos",
    status: "executing",
    progress: 0.5,
    steps: [
      { id: "s1", title: "Validar substância no novo município", detail: "Equipe e estrutura física em São José dos Campos.", status: "done", assignee: "RH + Jurídico", due: "2026-06-05", document: "laudo-substancia.pdf" },
      { id: "s2", title: "Alterar contrato social e inscrição municipal", detail: "Registro na JUCESP e inscrição na prefeitura.", status: "done", assignee: "Jurídico Societário", due: "2026-06-15", document: "alteracao-contratual.pdf" },
      { id: "s3", title: "Revisar contratos para o novo local de prestação", detail: "Aditivos contratuais e notas no novo município.", status: "doing", assignee: "Jurídico", due: "2026-06-28" },
      { id: "s4", title: "Reconfigurar emissão de NFS-e", detail: "Configurar o ERP para o novo município e alíquota.", status: "todo", assignee: "TI Fiscal", due: "2026-07-05" },
    ],
    audit: [
      { id: "a1", at: "2026-05-29T10:00:00Z", actor: "Vega (Agente)", action: "Oportunidade aberta", detail: "Detectou Lei Municipal 10.912/2026 e cruzou com a AcmeTech." },
      { id: "a2", at: "2026-05-31T16:20:00Z", actor: "Helena Vasconcelos (Tributarista)", action: "Execução aprovada", detail: "Aprovou condicionada à comprovação de substância." },
    ],
  },
];

export const SAVINGS: SavingsSummary = {
  currency: "BRL",
  realizedYtd: 14_820_000,
  inExecution: 5_900_000,
  projected12m: 38_400_000,
  feeBase: 14_820_000,
  feeRate: 0.18,
  feeDue: 2_667_600,
  byQuarter: [
    { quarter: "2025-Q3", realized: 2_100_000, projected: 2_100_000 },
    { quarter: "2025-Q4", realized: 3_640_000, projected: 3_640_000 },
    { quarter: "2026-Q1", realized: 4_180_000, projected: 4_180_000 },
    { quarter: "2026-Q2", realized: 4_900_000, projected: 6_400_000 },
    { quarter: "2026-Q3", realized: 0, projected: 9_200_000 },
    { quarter: "2026-Q4", realized: 0, projected: 12_880_000 },
  ],
  records: [
    { id: "sav-1", opportunityId: "opp-iss-sjc", playTitle: "ISS reduzido da AcmeTech (parcial)", type: "jurisdiction", realizedGain: 560_000, quarter: "2026-Q2", reconciled: true, capturedAt: "2026-06-15" },
    { id: "sav-2", opportunityId: "opp-lei-do-bem", playTitle: "Lei do Bem — exercício 2025", type: "credit", realizedGain: 2_980_000, quarter: "2026-Q1", reconciled: true, capturedAt: "2026-03-28" },
    { id: "sav-3", opportunityId: "opp-insumo", playTitle: "PIS/COFINS sobre insumos (1ª leva)", type: "classification", realizedGain: 1_360_000, quarter: "2026-Q1", reconciled: true, capturedAt: "2026-02-19" },
    { id: "sav-4", opportunityId: "opp-reintegra", playTitle: "Reintegra majorado — 4º tri/2025", type: "credit", realizedGain: 920_000, quarter: "2025-Q4", reconciled: true, capturedAt: "2025-12-10" },
    { id: "sav-5", opportunityId: "opp-subvencao", playTitle: "Subvenção de ICMS — recuperação parcial", type: "credit", realizedGain: 2_720_000, quarter: "2026-Q2", reconciled: false, capturedAt: "2026-06-20" },
    { id: "sav-6", opportunityId: "opp-icms-sc", playTitle: "Crédito presumido ICMS/SC — piloto", type: "incentive", realizedGain: 3_280_000, quarter: "2025-Q4", reconciled: true, capturedAt: "2025-11-22" },
  ],
};

export const AGENT_RECS: AgentRecommendation[] = [
  {
    id: "rec-1",
    kind: "window_closing",
    title: "Janela do crédito presumido de ICMS/SC fecha em breve",
    body: "O Termo de Adesão ao Regime Especial da SEF/SC encerra em poucos dias. Posso preparar o plano de execução e a checklist agora.",
    impact: 16_920_000,
    confidence: 0.86,
    opportunityId: "opp-icms-sc",
    createdAt: "2026-06-24T08:10:00Z",
  },
  {
    id: "rec-2",
    kind: "new_opportunity",
    title: "Nova oportunidade: Reintegra a 3% nas exportações",
    body: "O Decreto 12.044/2026 elevou o Reintegra para 3%. Cruzei com suas exportações de R$ 124 mi/ano — ganho estimado de R$ 3,72 mi.",
    impact: 3_720_000,
    confidence: 0.88,
    opportunityId: "opp-reintegra",
    createdAt: "2026-06-19T15:42:00Z",
  },
  {
    id: "rec-3",
    kind: "reconcile",
    title: "Conciliar R$ 2,72 mi da subvenção para fechar o success fee",
    body: "A recuperação da subvenção de ICMS precisa de conciliação bancária para entrar na base do success fee deste trimestre.",
    impact: 2_720_000,
    confidence: 0.93,
    opportunityId: "opp-subvencao",
    createdAt: "2026-06-21T11:05:00Z",
  },
];

// ── Painel do Dono (0C) ──────────────────────────────────────────────────────
export const OWNER_KPIS: OwnerKpis = {
  mrr: 487_400,
  mrrDelta: 0.114,
  activeTenants: 38,
  tenantsDelta: 6,
  aiSpend: 28_900,
  capturedNet: 312_800_000,
  errorRate: 0.0021,
  mrrSeries: [241, 268, 284, 309, 327, 351, 372, 398, 421, 444, 463, 487],
};

export const TENANTS: Tenant[] = [
  { id: "t-acme", name: "Acme Participações S.A.", plan: "Estrutura", status: "active", mrr: 24_900, users: 14, capturedNet: 14_820_000, aiSpend: 1_840, locale: "pt-BR", sector: "industry" },
  { id: "t-brava", name: "Brava Agroindustrial", plan: "Execução", status: "active", mrr: 39_900, users: 22, capturedNet: 41_200_000, aiSpend: 3_120, locale: "pt-BR", sector: "agribusiness" },
  { id: "t-nimbus", name: "Nimbus Tecnologia", plan: "Radar", status: "trial", mrr: 0, users: 6, capturedNet: 0, aiSpend: 410, locale: "en", sector: "tech" },
  { id: "t-petra", name: "Petra Energia S.A.", plan: "Execução", status: "active", mrr: 39_900, users: 31, capturedNet: 88_600_000, aiSpend: 5_270, locale: "pt-BR", sector: "energy" },
  { id: "t-lumen", name: "Lumen Varejo", plan: "Estrutura", status: "past_due", mrr: 24_900, users: 11, capturedNet: 6_400_000, aiSpend: 980, locale: "pt-BR", sector: "retail" },
  { id: "t-yangtze", name: "扬子物流 (Yangtze Logística)", plan: "Estrutura", status: "active", mrr: 24_900, users: 9, capturedNet: 12_100_000, aiSpend: 1_220, locale: "zh-CN", sector: "logistics" },
  { id: "t-meridien", name: "Groupe Méridien Santé", plan: "Execução", status: "active", mrr: 39_900, users: 18, capturedNet: 33_900_000, aiSpend: 2_640, locale: "fr-FR", sector: "health" },
];

export const PLANS: Plan[] = [
  {
    id: "plan-radar",
    name: "Radar",
    tagline: "Veja cada janela abrir.",
    price: 9_900,
    period: "month",
    feeRate: 0,
    features: [
      "Radar normativo federal, estadual e municipal",
      "Relevância cruzada com a sua estrutura",
      "Copiloto Vega em todas as telas",
      "Alertas por e-mail e WhatsApp",
      "4 idiomas",
    ],
    entitlements: ["radar", "structure", "copilot", "whatsapp"],
    quotas: { users: 5, jurisdictions: 3, aiCredits: "5k/mês" },
  },
  {
    id: "plan-structure",
    name: "Estrutura",
    tagline: "Simule a jogada antes de mover.",
    price: 24_900,
    period: "month",
    popular: true,
    feeRate: 0.18,
    features: [
      "Tudo do Radar",
      "Simulador de impacto fiscal/jurídico",
      "Detalhe da jogada recomendada",
      "Agente autônomo de decisão",
      "Conciliação da economia capturada",
    ],
    entitlements: ["radar", "structure", "simulator", "opportunities", "copilot", "agent", "whatsapp", "savings"],
    quotas: { users: 15, jurisdictions: 10, aiCredits: "25k/mês" },
  },
  {
    id: "plan-execution",
    name: "Execução",
    tagline: "Da norma à jogada protocolada.",
    price: 39_900,
    period: "month",
    feeRate: 0.15,
    features: [
      "Tudo da Estrutura",
      "Execução assistida com aprovação",
      "Trilha de auditoria imutável",
      "Connectors de ERP e assinatura",
      "Número de WhatsApp dedicado",
    ],
    entitlements: ["radar", "structure", "simulator", "opportunities", "execution", "copilot", "agent", "whatsapp", "savings", "connectors"],
    quotas: { users: "∞", jurisdictions: "∞", aiCredits: "100k/mês" },
  },
];

export const FEATURE_FLAGS: FeatureFlag[] = [
  { module: "opportunities", label: "Oportunidades", scope: "global", enabled: true, rollout: 100 },
  { module: "radar", label: "Radar normativo", scope: "global", enabled: true, rollout: 100 },
  { module: "simulator", label: "Simulador", scope: "plan", enabled: true, rollout: 100 },
  { module: "execution", label: "Execução assistida", scope: "plan", enabled: true, rollout: 100 },
  { module: "agent", label: "Agente autônomo", scope: "plan", enabled: true, rollout: 80 },
  { module: "connectors", label: "Connectors de ERP", scope: "tenant", enabled: true, rollout: 35 },
  { module: "whatsapp", label: "Controle por WhatsApp", scope: "global", enabled: true, rollout: 100 },
  { module: "savings", label: "Economia capturada", scope: "plan", enabled: true, rollout: 100 },
];

export const AUDIT_LOG = [
  { id: "g1", at: "2026-06-24T08:10:00Z", actor: "Vega (Agente)", tenant: "Acme Participações", action: "Recomendação enviada", detail: "Janela ICMS/SC fechando — push de WhatsApp." },
  { id: "g2", at: "2026-06-23T19:48:00Z", actor: "platform_owner", tenant: "Petra Energia", action: "Impersonation iniciada", detail: "Suporte ao onboarding do REPETRO." },
  { id: "g3", at: "2026-06-23T14:02:00Z", actor: "Helena Vasconcelos", tenant: "Acme Participações", action: "Execução aprovada", detail: "Subvenção de ICMS — R$ 4,78 mi." },
  { id: "g4", at: "2026-06-22T10:31:00Z", actor: "platform_staff", tenant: "Lumen Varejo", action: "Cobrança reprocessada", detail: "Fatura em atraso reprocessada." },
  { id: "g5", at: "2026-06-21T11:05:00Z", actor: "Vega (Copiloto)", tenant: "Brava Agroindustrial", action: "Simulação executada", detail: "Crédito presumido de Funrural." },
];
